### ISSUE TITLE
Oneshot: idents for manager role are not checked against production AD

### ISSUE THREAD

**Issue by tronghn** [navikt/kafka-adminrest#10]
The oneshot endpoint fails if the payload contains an ident that does not exist in the respective environment this application is deployed in.

As all requests are validated against production AD regardless of environment, the `MANAGER` role check should also be validated in the same manner.

**Comment by ybelMekk** [comment]
Trong can u explain this one for me?
So Authenticated user (in production ldap) - should not be checked in code if existing in "local ldap environment"? line 90 - Oneshot.kt - "!ldap.userExists(currentUser)" ?

**Comment by tronghn** [comment]
Authenticated requests are already checked against production AD in LDAPAuthenticate.kt. It might be unnecesary to check for the authenticated user's existence in any other environment.

Then again, the manager groups are per environment - which naturally requires the user to exist in that environment. I see that the case is actually reasonably handled in the code now. The issue is more related to inconsistencies between AD environments, so I'm going to close this.
